#!/bin/bash

# This bash script get an upstream copy of the Mozilla PDF.js package

pdfjsVersion=2.13.216

mkdir -p tmp

if [ ! -f tmp/pdfjs.gz.tar ]; then
  pushd tmp
  wget --output-document=pdfjs.gz.tar \
    https://github.com/mozilla/pdf.js/archive/refs/tags/v${pdfjsVersion}.tar.gz
  popd
fi

rm -rf pdfjs
mkdir -p pdfjs

pushd pdfjs
tar xvf ../tmp/pdfjs.gz.tar --strip-component=1

pushd web
sed 's|url(images|url(pdfjs-dist:web/images|' viewer.css -i
sed 's|pdfjs-web/|./|' viewer.js -i
for jsFile in *.js ; do
  echo fixing $jsFile
  sed 's|pdfjs-libs|pdfjs-dist|g' $jsFile -i
  sed 's|pdfjs-lib|pdfjs-dist|g' $jsFile -i
  sed 's|\"pdfjs/core/worker.js|\"pdfjs-dist/build/pdf.worker.js|g' $jsFile -i
done
ag pdfjs-lib
popd

rm -rf ../web
mv web ..

rm -rf ../external
mv external ..

rm -rf ../extensions
mv extensions ..

popd

cp localChanges/* web

rm -rf pdfjs
