#!/bin/bash

# This bash script updates the pdf.js git submodule to a *new* HEAD

cd pdfjs

git fetch

echo ""

git status -b | grep -v nothing

echo ""

#git log --oneline origin/main -10

git tag --color --sort version:refname          \
  --format "%(refname:short)	%(committerdate)" \
| tail

echo ""

echo "Please enter a commit or tag from the list above"

read -p "(or ^C to abort): " newCommit

if [ -n "$newCommit" ] ; then

  git checkout -q $newCommit

fi
