#!/bin/bash

# This bash script updates the pdf.js git submodule to a *new* HEAD

cd pdfjs

git fetch

echo ""

#git log --oneline origin/main -10

git tag -n10 --color --sort version:refname                          \
  --format "%(refname:short)  %(committerdate)  %(contents:subject)"

echo ""

echo "Please enter a commit or tag from the list above"

read -p "(or ^C to abort): " newCommit

if [ -n "$newCommit" ] ; then

  git checkout -q $newCommit

fi
